### PR TITLE
CircleCI project setup for both arm64 and amd64

### PR DESCRIPTION
**Pull request by jamesmortensen**
Since CircleCI has ARM runners (AWS Graviton) it may be beneficial to run CI workflows on both ARM and Intel/AMD.

The two jobs run, but there is something complaining about the .circleci folder.  If you know how to exclude the folder then we can run tests on both architectures. 

See https://app.circleci.com/pipelines/github/jamesmortensen/slime/4/workflows/b4fa3bb5-a113-4ba5-8dcc-2a52c15cd153

### CODE REVIEW

**Comment by jamesmortensen** [comment]
I tried adding a license to .circleci/config.yml as it seems the linter is looking for licenses.  I still cannot get the linter to pass.  Here's the latest log:  https://app.circleci.com/pipelines/github/jamesmortensen/slime/8/workflows/60880ff2-4f0c-403d-a6cd-7f04e93663ec/jobs/12

If the linter passes, then we can compare apples to apples by running tests for both AMD64 and ARM64 in Ubuntu 20.04 Linux.

**Comment by davidpcaldwell** [comment]
@jamesmortensen thanks, I'll be able to get this fixed up pretty easily. Hopefully I can get to it today!

**Comment by davidpcaldwell** [comment]
Thank you, @jamesmortensen!

**Comment by jamesmortensen** [comment]
You're welcome! @davidpcaldwell Still not sure what is happening on Mac M1, but hoping being able to run on CircleCI can help debug any ARM specific issues.  We can see here on CircleCI that tests on AMD64 pass, but there are failures on ARM64.  Not sure if they're related to Seleniarm or some other issues.  Hoping this helps you debug it further! :)

**Comment by jamesmortensen** [comment]
https://app.circleci.com/pipelines/github/jamesmortensen/slime?branch=circleci-project-setup

**Pull request merged**
